version: '3.9'

networks:
  postgres-network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "postgrespwd"
    ports:
      - "15432:5432"
    volumes:
      - data/db
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "devopspro@desafio.com.br"
      PGADMIN_DEFAULT_PASSWORD: "postgrespwd"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-network
