version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/data/db
    environment:
      POSTGRES_DB: kubedevnews
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd

  pgadmin4:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - '8081:80'
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: 'devopspro@desafio.com'
      PGADMIN_DEFAULT_PASSWORD: postgrespwd

  app:
    container_name: kube-news
    image: danilopetruce/kube-news:latest
    restart: always

    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_DATABASE: kubedevnews
      DB_USERNAME: user
      DB_PASSWORD: pwd

volumes:
  postgres-data:
