version: "3.9"

services:
  app:
    image: danilopetruce/rotten-potatoes:latest
    build:
      dockerfile: ./Dockerfile
      context: ./src
    ports:
      - 5000:5000
    depends_on:
      - db
    networks:
      - rotten-potatoes_net
    environment:
      MONGODB_DB: admin
      MONGODB_HOST: db
      MONGODB_PORT: 27017
      MONGODB_USERNAME: mongouser
      MONGODB_PASSWORD: mongopwd

  db:
    image: mongo:4.4.3
    restart: always
    networks:
      - rotten-potatoes_net
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
    volumes:
      - rotten-potatoes_vol:/data/db

networks:
  rotten-potatoes_net:
    driver: bridge

volumes:
  rotten-potatoes_vol:
